name: CI/CD Pipeline Frontend
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    services:
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 10s
          --health-retries 10
    steps:
      # Étape 1 : Cloner le dépôt
      - name: Checkout Code
        uses: actions/checkout@v3

      # Étape 2 : Installer Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.4'

      # Étape 3 : Installer les dépendances
      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      # Étape 5 : Lancer le frontend (Streamlit)
      - name: Start Frontend (main.py)
        run: |
          nohup streamlit run main.py &


